---
title: "Time Series and Forecasting -  Final Project - Test with Beijing Air Data"
author: "Klismam F. Pereira"
date: "19/12/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
___  

```{r imports include=FALSE}
library(astsa)
library(fpp2)
library(xts)
library(TSstudio)
library(tidyr)
```

```{r}
df <- read.csv2("PRSA_Data_Dongsi_20130301-20170228.csv", sep = ",")
df <- df %>% unite(date, c(year,month, day), sep="-", remove = FALSE) %>% unite(date_time, c(date, hour), sep=" ", remove = FALSE) 

df$PM2.5 <- as.numeric(df$PM2.5)

str(df)
```

```{r}
# https://stackoverflow.com/questions/33782218/how-to-create-a-time-series-of-hourly-data?rq=1
# first_hour <- 24*(as.Date(df$date_time[1]) - as.Date("2013-1-1 00:00:00"))
first_hour <- difftime(as.Date(df$date_time[1]),as.Date("2013-1-1 00:00:00"), units="hours")
first_year <- format(as.Date(df$date_time[1]), "%Y")
first_month <- format(as.Date(df$date_time[1]), "%m")
first_day <- format(as.Date(df$date_time[1]), "%d")

PM2.5_ts <- ts(df$PM2.5, start=c(first_year, first_hour), frequency=24*365)

tsplot(PM2.5_ts)
PM2.5_acf_pacf <- acf2(df$PM2.5)
```  

```{r}
unique.years <- unique(df$year)
for (y in unique.years) {
        tsplot(window(x=PM2.5_ts, start=y, end=y+1), main=y, minor = FALSE)
}
```  

```{r}
diff_PM2.5 <- diff(df$PM2.5, 12)
tsplot(diff_PM2.5)
diffPM2.5_acf_pacf <- acf2(diff_PM2.5)
```  

```{r experimenting_mean}
unique.months <- c(1:12)

monthly.means <- c()
years.list <- c()
months.list <- c()

for (y in unique.years) {
        for (m in unique.months) {
                temp.PM2.5 <- df$PM2.5[
                        ( df$year == y ) & ( df$month == m )
                ]
                m.mean <- mean(temp.PM2.5, na.rm = TRUE)
                if (!is.na(m.mean)) {
                        monthly.means <- c(monthly.means, m.mean)
                        years.list <- c(years.list, y)
                        months.list <- c(months.list, m)
                }
                
        }
}

cbind(years.list, months.list, monthly.means)

first_year <- years.list[1]
first_month <- months.list[1]

PM2.5_ts <- ts(monthly.means, start=c(first_year, first_month), frequency=12)

tsplot(PM2.5_ts)
PM2.5_acf_pacf <- acf2(df$PM2.5)

ggmonthplot(PM2.5_ts)
```  



